name: Practice Workflow
on: [push, workflow_dispatch]

jobs:
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Say Hiiii!
        run: echo "Hiiii!"
      - name: Say Good Bye
        run: echo "Good Bye"

  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi
        working-directory: ./path/to/your/project
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: my-files
          path: |
            my-files
            package.json
